cosmosdb: # shared among spaces
  account: functions-{{.Values.global.envName}}
  authKey: functions-{{.Values.global.envName}}-authkey
  consistency: Strong
  resourceGroup:
    name: {{.Values.global.resourceGroup.name}}
    location: {{.Values.global.resourceGroup.location}}
  dbs:
    events:
      collections:
        - name: amps
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
        - name: voltage
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
        - name: temperature
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
    anomalies:
      collections:
        - name: amps
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
        - name: voltage
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
        - name: temperature
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
    alerts:
      collections:
        - name: amps
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
        - name: voltage
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"
        - name: temperature
          throughput: 400
          partition: "env_time, dc_name"
          sps:
            - name: bulkUpsert
              file: "/cosmosdb/procedures/bulkUpsert.js"
            - name: bulkDelete
              file: "/cosmosdb/procedures/bulkDelete.js"